#!/bin/bash

ops=(
"lvec"
"svec"
"stvec"
"2piI1_P100"
"2piI1_P110"
"2piI1_P111"
"2piI1_P200"
)

files=(
"vec"
"vec"
"tvec"
"2piI1_P100"
"2piI1_P110"
"2piI1_P111"
"2piI1_P200"
)

args=(
""
'--replace_POS local \\\"\\\"'
'--replace_POS local \\\"\\\"'
'--replace_POS local \\\"\\\"'
'--replace_POS local \\\"\\\"'
'--replace_POS local \\\"\\\"'
'--replace_POS local \\\"\\\"'
)

n=${#ops[@]}
for ((i=0;i<n;i++))
do

    eval "opL=\"${ops[$i]}\""
    eval "fileL=\"${files[$i]}\""
    eval "argL=\"${args[$i]}\""
    argL=$(echo $argL | sed 's/POS/left/g')

    for ((j=i;j<n;j++))
    do
        
            eval "opR=\"${ops[$j]}\""
            eval "fileR=\"${files[$j]}\""
            eval "argR=\"${args[$j]}\""
            argR=$(echo $argR | sed 's/POS/right/g')

	    for ((m=0;m<3;m++))
	    do
		dst=000_T1M_${m}

		mkdir -p $dst
		eval "exe=\"../wick ../operators/${fileL}.$dst ../operators/${fileR}.$dst $argL $argR --replace_right t t0 --avoid_source t --ignore_hints\""
		echo $exe
		eval "$exe > $dst/${opL}-${opR}.contr"
		cat $dst/${opL}-${opR}.contr | awk 'BEGIN{ hasTsrc=0; }{
 if ($1=="LIGHT" && $(NF) == "t")hasTsrc=1;
 if ($1=="LIGHTBAR" && $2 == "t")hasTsrc=1;
}END{ print "hasTsrc " hasTsrc; }' > $dst/${opL}-${opR}.flags
	    done
    done

done

# remove ones that we can do better with other methods
rm -f */lvec-lvec.*
